# Project identification
sonar.host.url=https://sonarcloud.io
sonar.organization=cloud-nation
sonar.projectKey=cloud-nation_frontend
sonar.projectName=frontend
sonar.projectVersion=1.0.0

# Language specific options
sonar.language=js
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.js
sonar.nodejs.executable=path/to/your/nodejs

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Token for authentication (replace with your SonarCloud token)
sonar.login=9408e3574935c428d6cecdb00ca0a4b4295c208e
